version: '3.8'

services:
  backend:
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    networks:
      - backend-network

networks:
  backend-network: