version: '3.8'

services:
  backend:
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    networks:
      - backend-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/front
    networks:
      - frontend-network
networks:
  backend-network:
  frontend-network: